### PR TITLE
refactor: expose 'levels' object and force readonly

### PR DESCRIPTION
**Pull request by hamed-musallam**

### CODE REVIEW

**Comment by targos** [comment]
why is this needed?

**Comment by hamed-musallam** [comment]
Do you mean why we need to expose the `levels` object?

to use the defined set of these constants once we need to check for `level` (which is an object that holds a number value indicating of the log is info, warn, ... etc)  and avoid mistyping numbers.


https://github.com/cheminfo/fifo-logger/blob/72d8b351a3c54398365832ea99c8a18a161688a3/src/levels.ts#L5-L27

**Comment by targos** [comment]
I understand that you expose it to use it. I don't understand why you want or think you need to use it.

**Comment by hamed-musallam** [comment]
In this case, we give each row a background color based on the level object

https://github.com/cheminfo/nmrium/blob/48e654bafba8cc91c7b3d28998caa0115dbb0187/src/component/header/LogsHistory.tsx#L63-L75

**Comment by targos** [comment]
You can fix that here without exposing the objects: https://github.com/cheminfo/fifo-logger/blob/72d8b351a3c54398365832ea99c8a18a161688a3/src/FifoLogger.ts#L7-L8

The types should be more specific to make your code safe.

**Comment by hamed-musallam** [comment]
can you check the PR and merge if it is LGTY?

**Pull request merged**
